env:
  node: true
  es6: true

extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:import/recommended'
  - 'plugin:import/typescript'
  - 'prettier'

plugins:
  - 'unused-imports'

rules:
  react/prop-types:
    - 2
    - skipUndeclared: true
  react/jsx-boolean-value: 2
  react/jsx-curly-brace-presence: 2
  react/self-closing-comp:
    - 2
    - component: true
      html: true
  import/order:
    - 2
    - alphabetize:
        order: 'asc'

settings:
  import/resolver:
    typescript: ''
  react:
    version: 'detect'

ignorePatterns:
  - 'public/'
  - 'coverage/'
