name: 'production deploy'

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Test

    env:
      ANALYTICS_TRACKING_ID: ${{ secrets.ANALYTICS_TRACKING_ID }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build --path-prefixes

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
