name: 'test'

on: pull_request

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Run test
        run: yarn test:coverage

      - name: Upload coverage
        uses: codecov/codecov-action@v2
